### PR TITLE
Fixing use of آمرداد in time.ir

### PR DESCRIPTION
**Pull request by tacrazymage**
This may solves issue #8
Sorry, I did not run the app and edited the code in my phone on the road 😬
so it may not solve the problem

Let me know if I should change anything

### CODE REVIEW

**Comment by pouriya** [comment]
Hi. Actually it starts with `اَ` (Arabic A with fatha) not `آ`. So it will be `(1575, 1614)`.
Thank you.

**Comment by tacrazymage** [comment]
Tnx, yes you are right
I fix that

**Comment by tacrazymage** [comment]
I have a question:
at the moment I just added second version of Mordad (اَمرداد) and not deleted the last one (مرداد)
because maybe developers of "time.ir" rollback their change (I dont know, maybe it is a temporary change)

what is your opinion?
should we keep that or delete the last one?

**Comment by pouriya** [comment]
Yes, We should keep that. Thank you very much. If you have a Twitter account, let me know in the next comment.

**Comment by pouriya** [comment]
Tir v20.07.26 is out. Thanks!

**Comment by tacrazymage** [comment]
Tnx for merge
DM you in twitter :D

**Pull request merged**
